[package]
name = "pyo3-question"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyo3_question"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
